### ISSUE TITLE
review (request) logging

### ISSUE THREAD

**Issue by JamieVangeysel** [groupclaes/fastify-elastic#10]
@LuckyWraptor is it usefull to continue logging; request received and response send events.
Currently.
When for example looking at logs for the endpoint brabopak/magage/users we get a lot of excess logs; 
<img width="1352" alt="image" src="https://github.com/groupclaes/fastify-elastic/assets/32323785/b83ede50-d4d2-4ace-a8e0-f9d744c5b494">

Log messages to disable/review

- [ ] Server listening at http://[::]:80
- [x] Sent response
- [x] Received request

**Comment by OhSoooLucky** [comment]
They can still be used for log aggregation, but filtered in logstash.

So request details (like an exception) can be aggregated in all logs from that request.
Where Logstash will use the received and sent log entries as delimiters

**Comment by JamieVangeysel** [comment]
But is there any merit if we keep these logs? Looks like a waste of storage to me 🫣

**Comment by JamieVangeysel** [comment]
Server listening at http://[::]:80 can only be disabled by passing a custom callback to the listen event
